config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :pokedex, only: %i[create]
  end

  resources :pokedex, only: %i[index show]

  root 'pokedex#index'
end

app/models/ability.rb
class Ability < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates_presence_of :detail_page_url, :weight, :number, :height, :collectibles_slug, :featured, :slug, :name,
                        :thumbnail_alt_text, :thumbnail_image
  validates :number, uniqueness: true

  has_many :pokemon_ability, dependent: :destroy
  has_many :abilities, through: :pokemon_ability

  has_many :pokemon_type, dependent: :destroy
  has_many :types, through: :pokemon_type

  has_many :pokemon_weakness, dependent: :destroy
  has_many :weaknesses, through: :pokemon_weakness
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/pokemon_weakness.rb
class PokemonWeakness < ApplicationRecord
  belongs_to :pokemon
  belongs_to :weakness
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true
end

app/models/weakness.rb
class Weakness < ApplicationRecord
  validates :name, presence: true
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/api/pokedex_controller.rb
class Api::PokedexController < Api::ApiController
  def create
    GeneratePokemonJob.perform_later
    render json: { message: 'Request Accepted' }, status: :accepted
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokedex_controller.rb
class PokedexController < ApplicationController
  before_action :set_pokemon_repository, only: %i[index show]

  def index
    @pokemons = if params[:query]
                  @pokemon_repository.search(params[:query], params[:page])
                else
                  @pokemon_repository.paginate(params[:page])
                end
  end

  def show
    @pokemon = @pokemon_repository.show(params['id'])
  end

  private

  def set_pokemon_repository
    @pokemon_repository = PokemonRepository.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav>
  <%=link_to "Pokédex", pokedex_index_url, class: "title" %>
  <div class="logo-wrapper">
    <%= image_tag("pokemon.png", class: "pokemon-logo")%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pokedex/_form_search.html.erb
<%= form_with url: "/pokedex", method: :get, class: "form-search" do |form| %>
  <div class="form-group">
    <%= form.label :query, "Encuentra tu Pokémon favorito" %>
    <%= form.text_field :query, class: "input-search", placeholder: "Ingresa nombre o número de pokédex" %>
    <%= form.submit "search", class: "submit-search" %>
  </div>
<% end %>

app/views/pokedex/_pokemon_card.html.erb
<div class="pokemon-card">
  <%=link_to pokedex_path(pokemon), class: "image-link" do %>
    <img class="pokemon-image" src=<%= pokemon.thumbnail_image %> alt="pokemon">
  <% end %>
  <p class="pokemon-number">N.<%= pokemon.number %></p>
  <h5 class="pokemon-name"><%= pokemon.name %></h5>
  <div class="abilities">
    <% pokemon.abilities.each do |ability| %>
      <span><%= ability.name %></span>
    <% end %>
  </div>
</div> 

app/views/pokedex/index.html.erb
<%= render "form_search"%>

<div class="flickr_pagination">
		<%= will_paginate @pokemons, :container => false,  :previous_label => 'Anterior', :next_label => 'Siguiente' %>
</div>

<div class="pokemon-container">
	<% @pokemons.each do |pokemon| %>
		<%= render "pokemon_card", pokemon: pokemon %>
	<% end %>
</div>

<div class="flickr_pagination">
	<%= will_paginate @pokemons, :container => false,  :previous_label => 'Anterior', :next_label => 'Siguiente' %>
</div>

app/views/pokedex/show.html.erb
<div class="pokemon-description">
  <%= link_to pokedex_index_path, class: "return" do %>
    &#171; regresar
  <% end %>
  <div class="name"><%= @pokemon.name %><span>N.<%= @pokemon.number %></span></div>
  <div class="pokemon-wrapper">
    <img class="pokemon-image" src=<%= @pokemon.thumbnail_image %> alt=<%= @pokemon.thumbnail_alt_text %>>
    <div class="pokemon-info">
      <h3>Información</h3>
      <div class="info-item">
        <span class="attribute-title">Altura</span>
        <span class="attribute-content"><%= @pokemon.height %> metros</span>
      </div>
      <div class="info-item">
        <span class="attribute-title">Categoría</span>
        <span class="attribute-content">No disponible</span>
      </div>
      <div class="info-item">
        <span class="attribute-title">Peso</span>
        <span class="attribute-content"><%= @pokemon.weight %> kilogramos</span>
      </div>
      <div class="info-item">
        <span class="attribute-title">Habilidad</span>
        <span class="attribute-content">
          <div class="abilities">
            <% @pokemon.abilities.each do |ability| %>
              <span>&#8226;<%= ability.name %></span>
            <% end %>
          </div>
        </span>
      </div>
    </div>
  </div>
  <div class="pokemon-wrapper">
    <div class="types">
      <h3>Tipo</h3>
      <% @pokemon.types.each do |type| %>
        <span><%= type.name %></span>
      <% end %>
    </div>
    <div class="weaknesses">
      <h3>Debilidad</h3>
      <% @pokemon.weaknesses.each do |weakness| %>
        <span><%= weakness.name %></span>
      <% end %>
    </div>
  </div>
</div> 